---
abstract: 'Less Boilerplate when you need lots of Instances'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  Class::MOP: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Iterator: 0
  MooseX::Types::Path::Class: 0
  Perl6::Junction: 0
  Scalar::Util: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-BuildInstanceOf
requires:
  Moose::Util::TypeConstraints: 0
  MooseX::Role::Parameterized: 0.13
  perl: 5.008001
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Role-BuildInstanceOf
  homepage: http://metacpan.org/release/MooseX-Role-BuildInstanceOf
  repository: git://github.com/jjn1056/MooseX-Role-BuildInstanceOf.git
version: 0.08
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@FLORA/@Basic/GatherDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@FLORA/@Basic/PruneCruft'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@FLORA/@Basic/ManifestSkip'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@FLORA/@Basic/MetaYAML'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::License
      name: '@FLORA/@Basic/License'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@FLORA/@Basic/Readme'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@FLORA/@Basic/ExtraTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@FLORA/@Basic/ExecDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@FLORA/@Basic/ShareDir'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@FLORA/@Basic/MakeMaker'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@FLORA/@Basic/Manifest'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@FLORA/@Basic/TestRelease'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@FLORA/@Basic/ConfirmRelease'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@FLORA/@Basic/UploadToCPAN'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@FLORA/MetaConfig'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@FLORA/MetaJSON'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@FLORA/PkgVersion'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@FLORA/PodSyntaxTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@FLORA/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@FLORA/PodCoverageTests'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@FLORA/MetaResources'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@FLORA/Authority'
      version: 1.005
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@FLORA/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@FLORA/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@FLORA/AutoPrereqs'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300002
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300002
x_authority: cpan:FLORA
