---
abstract: 'Less Boilerplate when you need lots of Instances'
author:
  - 'John Napiorkowski C<< <jjnapiork@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  MooseX::Iterator: 0
  MooseX::Types::Path::Class: 0
  Perl6::Junction: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::Role::BuildInstanceOf
name: MooseX-Role-BuildInstanceOf
no_index:
  directory:
    - inc
    - t
requires:
  Class::MOP: 0.94
  Moose: 0.92
  MooseX::Role::Parameterized: 0.13
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/MooseX-Role-BuildInstanceOf.git
version: 0.05
